update aicoe-ci config to build container image using repo containerfile
operate-first/hitchhikers-guide pull request #121
Opened 2021-12-13 19:59 UTC by 4n4nd

Resolves https://github.com/operate-first/hitchhikers-guide/issues/120

2021-12-13 20:00 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **humairak** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @humairak` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fhitchhikers-guide).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/hitchhikers-guide/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["humairak"]} -->

2021-12-13 20:05 UTC, harshad16 commented
/retest

2021-12-13 20:12 UTC, mimotej commented
/lgtm

2021-12-13 20:17 UTC, 4n4nd commented
/hold

2021-12-14 05:36 UTC, 4n4nd commented
I think the Containerfile is building a base image that we could use to build tha hitchhiker's guide image.
@tumido is that the case here?

2021-12-14 16:09 UTC, sesheta commented
New changes are detected. LGTM label has been removed.

2021-12-14 16:15 UTC, harshad16 requested changes
need some more further changes

2021-12-14 16:15 UTC, harshad16 commented on .aicoe-ci.yaml
> +  - name: builder-image
As we are using the overlays method, and it is described in this PR
that the `overlays_dir` is `.`

then the pipeline would try to look for the sub_dir with name `builder-image` at the root
for the containerfile


and same fo the hitchhikers-guide.

2021-12-14 17:46 UTC, 4n4nd commented
Looks like we don't need this PR anymore, the builder image is directly being built in quay and the htg image should build

2021-12-14 17:46 UTC, closed without merging