feat: create basic structure for jupyterbook guides
operate-first/hitchhikers-guide pull request #2
Opened 2021-08-09 07:33 UTC by mimotej

Basic structure for jupyterbook tutorials (as part of https://github.com/operate-first/support/issues/326). Structure is inspired by Operate first website https://www.operate-first.cloud/ .

2021-08-09 07:34 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **tumido** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @tumido` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fhitchhikers-guide).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/hitchhikers-guide/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["tumido"]} -->

2021-08-09 11:24 UTC, tumido requested changes
This is a good start @mimotej :+1:

Can you please change few things around?

1. Move `content/*` to the repo root ( there's no need to nest all meaningful repository content into a folder).
2. Change the title per suggestion
3. Can you please add/change the README to actually describe the repo purpose? You can leave the current content of the README below (and nest it from H1 to H2 or something)
4. Can you please create a basic `Pipfile` (and a lock file) so people can do just `pipenv install` and have the dev setup ready?
5. Can you please include some "how to" for dev setup? Like how to build it etc?

You can read more on Pipenv here: https://pipenv.pypa.io/en/latest/

2021-08-09 11:24 UTC, tumido commented on content/_config.yml
> +title: "Operate-first tutorials"
Let's keep the repo name here:

```suggestion
title: Hitchhiker's Guide to Operate First
```

2021-08-09 11:29 UTC, tumido requested changes
\+ one more thing, can you please add `.gitignore` for files generated by `jypyter-book build`, please? So it doesn't annoy developers and they don't accidentally include generated files in a PR?

2021-08-10 12:27 UTC, mimotej commented on content/_config.yml
> +title: "Operate-first tutorials"
Resolved in latest commit

2021-08-11 09:11 UTC, tumido approved these changes
/lgtm
/approve

Looks great @mimotej, good job! :+1: I think as a scaffold this can be merged now and with next PR you can focus on the content :slightly_smiling_face:

2021-08-11 09:11 UTC, merged